brew install \
    aom
    autoconf \
    automake \
    avr-binutils \
    avr-gcc \
    avr-gcc@7 \
    avrdude \
    awscli \
    bash \
    cairo \
    cask \
    cfssl \
    coreutils \
    dark-mode \
    dep \
    dfu-programmer \
    docker-machine \
    docker-machine-driver-xhyve \
    eksctl \
    eksctl-aws-iam-authenticator \
    emacs \
    ffmpeg \
    flac \
    fluxctl \
    fontconfig \
    freetype \
    frei0r \
    fribidi \
    gcc-arm-none-eabi \
    gdbm \
    gettext \
    giflib \
    git-crypt \
    glib \
    gmp \
    gnutls \
    go \
    goreleaser \
    graphite2 \
    grep \
    harfbuzz \
    htop \
    httpie \
    icu4c \
    ilmbase \
    imagemagick \
    isl \
    jemalloc \
    jpeg \
    jq \
    kubernetes-cli \
    kubeseal \
    lame \
    leptonica \
    libass \
    libbluray \
    libde265 \
    libelf \
    libev \
    libevent \
    libffi \
    libftdi0 \
    libgpg-error \
    libheif \
    libhid \
    libidn2 \
    libksba \
    libmpc \
    libogg \
    libomp \
    libpng \
    libsamplerate \
    libsndfile \
    libsoxr \
    libtasn1 \
    libtermkey \
    libtiff \
    libtool \
    libunistring \
    libusb \
    libusb-compat \
    libuv \
    libvorbis \
    libvpx \
    libvterm \
    libyaml \
    little-cms2 \
    luajit \
    make \
    mpfr \
    msgpack \
    ncurses \
    nettle \
    node \
    oniguruma \
    opencore-amr \
    openexr \
    openjpeg \
    openssl \
    openssl@1.1 \
    opus \
    p11-kit \
    packer \
    pcre \
    pixman \
    pkg-config \
    pwgen \
    python \
    readline \
    rtmpdump \
    rubberband \
    sdl2 \
    shellcheck \
    snappy \
    speedtest-cli \
    speex \
    sqlite \
    terraform \
    tesseract \
    thefuck \
    theora \
    tmux \
    tree \
    unibilium \
    watch \
    watchman \
    webp \
    wget \
    x264 \
    x265 \
    xhyve \
    xvid \
    xz \
    yarn \
    zlib \
    zsh-syntax-highlighting

brew cask install \
    1password \
    alfred \
    brave-browser \
    google-cloud-sdk \
    keybase \
    qmk-toolbox \
    spotify \
    sublime-text \
    virtualbox\
    1password-cli \
    authy \
    discord \
    gpg-suite \
    lulu \
    slack \
    steam \
    typora \
    whatsapp\
    agenda \
    battle-net \
    docker \
    iterm2 \
    postman \
    spark \
    sublime-merge \
    vagrant