brew install \
    automake \
    avr-binutils \
    aws-iam-authenticator \
    avr-gcc \
    avr-gcc@7 \
    avrdude \
    awscli \
    bash \
    bash-completion \
    build-essential \
    cask \
    cfssl \
    coreutils \
    dark-mode \
    dep \
    dfu-programmer \
    docker-machine \
    docker-machine-driver-xhyve \
    eksctl \
    ffmpeg \
    flac \
    fluxctl \
    gdbm \
    gmp \
    gnu-sed \
    go \
    goreleaser \
    grep \
    hadolint \
    htop \
    httpie \
    jq \
    kubectx \
    kubernetes-cli \
    kubeseal \
    kustomize \
    make \
    netcat \
    nmap \
    node \
    oniguruma \
    openssh \
    openssl \
    packer \
    pwgen \
    python3 \
    readline \
    shellcheck \
    speedtest-cli \
    sqlite \
    telnet \
    terraform \
    tesseract \
    thefuck \
    tmux \
    tree \
    vim \
    watch \
    watchman \
    wget \
    yarn \
    yq


brew cask install \
    1password \
    alfred \
    google-backup-and-sync \
    google-cloud-sdk \
    google-chrome \
    keybase \
    qmk-toolbox \
    spotify \
    sublime-text \
    virtualbox\
    1password-cli \
    discord \
    gpg-suite \
    lulu \
    slack \
    steam \
    typora \
    whatsapp\
    docker \
    iterm2 \
    postman \
    spark \
    sublime-merge \
    vagrant